services:
  - type: web
    name: astro-calculator
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PORT
        value: 10000
